//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: System.Reflection.AssemblyCompanyAttribute("Numan Koncept AB - Sweden")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright c 2023")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Beware of BIG BUGS!!! Use at own risk!!!")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("MenuMaker")]
[assembly: System.Reflection.AssemblyTitleAttribute("MenuMaker")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("")]

// Generated by the MSBuild WriteCodeFragment class.

[assembly: ComVisibleAttribute(false)]